export const funderQualificationMatrix = [
  {
    funder: 'Arena Funding Source',
    paperType: 'B-C',
    minimumRevenueAnnual: 240000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 550,
    maxPosition: 3,
    position1st: 'Yes',
    stateRestrictions: [
      'PR',
      'HI',
    ],
    insuffientFundsNSF: [
      4,
      11,
    ],
    negativeDays: [
      4,
      11,
    ],
    minimumMonthlyDepositcount: 5,
    minimumTimeInBusinessMonths: 9,
    minAvgDailyBalance: 0,
    minFundingAmount$: 25000,
    maxFundingAmount$: 0,
    restrictedIndustries: [
      'Transportation and Warehousing',
      'Automobile Dealers & Parts',
    ],
    tier: 4,
  },
  {
    funder: 'Balboa Capital',
    paperType: 'A - B',
    minimumRevenueAnnual: 300000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 600,
    maxPosition: 2,
    position1st: 'Yes',
    stateRestrictions: [
    ],
    insuffientFundsNSF: [
      3,
      9,
    ],
    negativeDays: [
      3,
      9,
    ],
    minimumMonthlyDepositcount: 7,
    minimumTimeInBusinessMonths: 12,
    minAvgDailyBalance: 2000,
    minFundingAmount$: 25000,
    maxFundingAmount$: 400000,
    restrictedIndustries: [
    ],
    tier: 1,
  },
  {
    funder: 'BITTY',
    pastSettledDefaults: true,
    minimumRevenueAnnual: 60000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 550,
    maxPosition: 3,
    position1st: 'Yes',
    stateRestrictions: [
    ],
    insuffientFundsNSF: [
      7,
      21,
    ],
    negativeDays: [
      7,
      21,
    ],
    minimumMonthlyDepositcount: 1,
    minimumTimeInBusinessMonths: 12,
    minFundingAmount$: 2000,
    maxFundingAmount$: 35000,
    restrictedIndustries: [
      'Automobile Dealers & Parts',
      'Gambling',
      'Retail Stores',
      'Finance and Insurance',
      'Arts, Entertainment and Recreation',
      'Political, Governmental, Or Public Organizations',
      'Adult Entertainment',
      'IT, Media or Publishing',
    ],
    tier: 4,
  },
  {
    funder: 'Breakout Capital',
    minimumRevenueAnnual: 500000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 600,
    maxPosition: 3,
    position1st: 'Yes',
    stateRestrictions: [
      'CA',
      'CO',
      'MT',
      'NJ',
      'NY',
      'NV',
      'ND',
      'OK',
      'RI',
      'SD',
      'VT',
    ],
    insuffientFundsNSF: [
      0,
      11,
    ],
    negativeDays: [
      3,
      11,
    ],
    minimumMonthlyDepositcount: 1,
    minimumTimeInBusinessMonths: 12,
    restrictedIndustries: [
    ],
    tier: 5,
  },
  {
    funder: 'CFGMS ',
    paperType: 'B-D',
    minimumRevenueAnnual: 84000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 500,
    maxPosition: 3,
    position1st: 'Yes',
    stateRestrictions: [
      'VI',
      'PR',
    ],
    insuffientFundsNSF: [
      4,
      12,
    ],
    negativeDays: [
      4,
      12,
    ],
    minimumMonthlyDepositcount: 3,
    minimumTimeInBusinessMonths: 6,
    minAvgDailyBalance: 100,
    minFundingAmount$: 5000,
    maxFundingAmount$: 750000,
    restrictedIndustries: [
    ],
    tier: 2,
  },
  {
    funder: 'Credibly',
    paperType: 'A - B',
    minimumRevenueAnnual: 300000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 550,
    maxPosition: 2,
    position1st: 'Yes',
    stateRestrictions: [
      'CA',
      'NY',
      'VA',
    ],
    insuffientFundsNSF: [
      7,
      7,
    ],
    negativeDays: [
      7,
      7,
    ],
    minimumMonthlyDepositcount: 1,
    minimumTimeInBusinessMonths: 6,
    minAvgDailyBalance: 1000,
    minFundingAmount$: 5000,
    maxFundingAmount$: 400000,
    restrictedIndustries: [
      'Adult Entertainment',
      'Gambling',
      'Firearm Sales',
      'Finance and Insurance',
      'Automobile Dealers & Parts',
      'Non-Profits',
      'Oil and Gas Extraction',
      'Real Estate',
      'Transportation and Warehousing',
    ],
    tier: 1,
  },
  {
    funder: 'Custom Capital',
    minimumRevenueAnnual: 120000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 500,
    maxPosition: 6,
    position1st: 'No',
    stateRestrictions: [
    ],
    insuffientFundsNSF: [
    ],
    negativeDays: [
    ],
    minimumTimeInBusinessMonths: 12,
    restrictedIndustries: [
    ],
    tier: 5,
  },
  {
    funder: 'DELTA',
    minimumRevenueAnnual: 120000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 500,
    maxPosition: 6,
    position1st: 'No',
    stateRestrictions: [
    ],
    insuffientFundsNSF: [
      8,
      8,
    ],
    negativeDays: [
      10,
      10,
    ],
    minimumMonthlyDepositcount: 1,
    minimumTimeInBusinessMonths: 12,
    restrictedIndustries: [
    ],
    tier: 5,
  },
  {
    funder: 'Elevate funding',
    paperType: 'C',
    minimumRevenueAnnual: 144000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 0,
    maxPosition: 1,
    position1st: 'Yes',
    stateRestrictions: [
    ],
    insuffientFundsNSF: [
      6,
      6,
    ],
    negativeDays: [
      6,
      6,
    ],
    minimumMonthlyDepositcount: 6,
    minimumTimeInBusinessMonths: 3,
    minAvgDailyBalance: 400,
    minFundingAmount$: 2500,
    maxFundingAmount$: 60000,
    restrictedIndustries: [
      'Adult Entertainment',
      'Agriculture, Forestry, Fishing and Hunting',
      'Automobile Dealers & Parts',
      'Legal Services',
      'Real Estate',
      'Travel Agencies',
      'Transportation and Warehousing',
    ],
    tier: 3,
  },
  {
    funder: 'Everest ',
    minimumRevenueAnnual: 60000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 550,
    maxPosition: 5,
    position1st: 'Yes',
    stateRestrictions: [
      'VA',
    ],
    insuffientFundsNSF: [
      5,
      15,
    ],
    negativeDays: [
      5,
      15,
    ],
    minimumMonthlyDepositcount: 1,
    minimumTimeInBusinessMonths: 3,
    minFundingAmount$: 5000,
    restrictedIndustries: [
      'Financial Institutions',
      'Automobile Dealers & Parts',
      'Legal Services',
    ],
    tier: 3,
  },
  {
    funder: 'Expansion / ECG',
    minimumRevenueAnnual: 72000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 550,
    maxPosition: 3,
    position1st: 'Yes',
    stateRestrictions: [
    ],
    insuffientFundsNSF: [
      6,
      9,
    ],
    negativeDays: [
      6,
      9,
    ],
    minimumMonthlyDepositcount: 2,
    minimumTimeInBusinessMonths: 6,
    minAvgDailyBalance: 600,
    minFundingAmount$: 0,
    maxFundingAmount$: 200000,
    restrictedIndustries: [
      'Adult Entertainment',
      'Automobile Dealers & Parts',
      'Gambling',
      'Political, Governmental, Or Public Organizations',
      'Legal Services',
      'Mining',
      'Oil and Gas Extraction',
      'Religious Organizations',
      'Travel Agencies',
    ],
    tier: 2,
  },
  {
    funder: 'Family Business Fund',
    minimumRevenueAnnual: 240000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 650,
    maxPosition: 3,
    position1st: 'Yes',
    stateRestrictions: [
      'CA',
      'PR',
    ],
    insuffientFundsNSF: [
      3,
      9,
    ],
    negativeDays: [
      3,
      9,
    ],
    minimumMonthlyDepositcount: 3,
    minimumTimeInBusinessMonths: 12,
    minAvgDailyBalance: 1000,
    minFundingAmount$: 5000,
    maxFundingAmount$: 100000,
    restrictedIndustries: [
      'Legal Services',
      'Real Estate',
      'Automobile Dealers & Parts',
    ],
    tier: 4,
  },
  {
    funder: 'Fintap',
    paperType: 'B+',
    minimumRevenueAnnual: 300000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 550,
    maxPosition: 3,
    position1st: 'Yes',
    stateRestrictions: [
      'CA',
    ],
    insuffientFundsNSF: [
      0,
      5,
    ],
    negativeDays: [
      0,
      5,
    ],
    minimumMonthlyDepositcount: 4,
    minimumTimeInBusinessMonths: 24,
    minAvgDailyBalance: '5% of Deposits',
    minFundingAmount$: 12000,
    maxFundingAmount$: 750000,
    restrictedIndustries: [
      'Automobile Dealers & Parts',
      'Legal Services',
      'Finance and Insurance',
    ],
    tier: 4,
  },
  {
    funder: 'FOX',
    paperType: 'B-C',
    minimumRevenueAnnual: 600000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 500,
    maxPosition: 5,
    position1st: 'Yes',
    stateRestrictions: [
      'PR',
    ],
    insuffientFundsNSF: [
      4,
    ],
    negativeDays: [
      4,
    ],
    minimumMonthlyDepositcount: 4,
    minimumTimeInBusinessMonths: 12,
    restrictedIndustries: [
      'Transportation and Warehousing',
      'Religious Organizations',
    ],
    tier: 2,
  },
  {
    funder: 'Funding Circle',
    paperType: 'A',
    minimumRevenueAnnual: 120000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 660,
    maxPosition: 1,
    position1st: 'Yes',
    stateRestrictions: [
    ],
    insuffientFundsNSF: [
      2,
      2,
    ],
    negativeDays: [
      1,
      1,
    ],
    minimumMonthlyDepositcount: 5,
    minimumTimeInBusinessMonths: 24,
    minFundingAmount$: 25000,
    maxFundingAmount$: 500000,
    restrictedIndustries: [
      'Real Estate',
      'Non-Profits',
      'Firearm Sales',
      'Gambling',
      'Adult Entertainment',
    ],
    tier: 1,
  },
  {
    funder: 'GetBackd',
    paperType: 'A - B',
    minimumRevenueAnnual: 600000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 625,
    maxPosition: 3,
    position1st: 'Yes',
    stateRestrictions: [
      'VI',
      'PR',
    ],
    insuffientFundsNSF: [
      3,
      9,
    ],
    negativeDays: [
      3,
      9,
    ],
    minimumMonthlyDepositcount: 9,
    minimumTimeInBusinessMonths: 12,
    minAvgDailyBalance: 2000,
    minFundingAmount$: 50000,
    maxFundingAmount$: 2000000,
    restrictedIndustries: [
      'Transportation and Warehousing',
      'Finance and Insurance',
      'Real Estate',
      'Legal Services',
    ],
    tier: 1,
  },
  {
    funder: 'GFE \n',
    paperType: 'A-D',
    minimumRevenueAnnual: 180000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 500,
    maxPosition: 4,
    position1st: 'Yes',
    stateRestrictions: [
      'PR',
      'HI',
    ],
    insuffientFundsNSF: [
      5,
      12,
    ],
    negativeDays: [
      5,
      12,
    ],
    minimumMonthlyDepositcount: 4,
    minimumTimeInBusinessMonths: 6,
    minAvgDailyBalance: 200,
    minFundingAmount$: 0,
    maxFundingAmount$: 750000,
    restrictedIndustries: [
    ],
    tier: 5,
  },
  {
    funder: 'Headway Capital',
    paperType: 'A',
    minimumRevenueAnnual: 250000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 675,
    maxPosition: 3,
    position1st: 'Yes',
    stateRestrictions: [
      'AR',
      'CT',
      'MI',
      'MT',
      'ND',
      'NV',
      'RI',
      'SD',
      'VT',
    ],
    insuffientFundsNSF: [
      0,
      0,
    ],
    negativeDays: [
      0,
      0,
    ],
    minimumMonthlyDepositcount: 8,
    minimumTimeInBusinessMonths: 6,
    minAvgDailyBalance: 0,
    minFundingAmount$: 5000,
    maxFundingAmount$: 100000,
    restrictedIndustries: [
      'Mining',
      'Oil and Gas Extraction',
      'Finance and Insurance',
      'Travel Agencies',
      'Automobile Dealers & Parts',
      'Gas Stations',
      'Gambling',
      'Adult Entertainment',
    ],
    tier: 1,
  },
  {
    funder: 'Idea Financial ',
    paperType: 'A-B',
    minimumRevenueAnnual: 180000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 650,
    maxPosition: 3,
    position1st: 'Yes',
    stateRestrictions: [
      'VT',
      'SD',
    ],
    insuffientFundsNSF: [
      6,
      12,
    ],
    negativeDays: [
      3,
      5,
    ],
    minimumMonthlyDepositcount: 8,
    minimumTimeInBusinessMonths: 36,
    minAvgDailyBalance: 5000,
    minFundingAmount$: 15000,
    maxFundingAmount$: 275000,
    restrictedIndustries: [
      'Agriculture, Forestry, Fishing and Hunting',
      'Mining',
      'Construction',
      'Automobile Dealers & Parts',
      'Real Estate',
      'Political, Governmental, Or Public Organizations',
      'Oil and Gas Extraction',
      'Firearm Sales',
      'Transportation and Warehousing',
      'Finance and Insurance',
      'Education',
    ],
    tier: 1,
  },
  {
    funder: 'IOU',
    paperType: 'A - B',
    minimumRevenueAnnual: 250000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 630,
    maxPosition: 2,
    position1st: 'Yes',
    stateRestrictions: [
      'MT',
      'SD',
      'ND',
      'MT',
      'NV',
      'VT',
      'HI',
      'DC',
    ],
    insuffientFundsNSF: [
      5,
      5,
    ],
    negativeDays: [
      5,
      5,
    ],
    minimumMonthlyDepositcount: 8,
    minimumTimeInBusinessMonths: 12,
    minAvgDailyBalance: 3000,
    minFundingAmount$: 15000,
    maxFundingAmount$: 1500000,
    restrictedIndustries: [
      'Adult Entertainment',
      'Legal Services',
      'Political, Governmental, Or Public Organizations',
      'Agriculture, Forestry, Fishing and Hunting',
      'Gambling',
      'IT, Media or Publishing',
      'Transportation and Warehousing',
      'Real Estate',
      'Mining',
      'Finance and Insurance',
      'Education',
    ],
    tier: 1,
  },
  {
    funder: 'Itria (Biz2Credit)',
    paperType: 'A',
    minimumRevenueAnnual: 600000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 600,
    maxPosition: 1,
    position1st: 'Yes',
    stateRestrictions: [
    ],
    insuffientFundsNSF: [
      0,
      6,
    ],
    negativeDays: [
      0,
      6,
    ],
    minimumMonthlyDepositcount: 0,
    minimumTimeInBusinessMonths: 24,
    minAvgDailyBalance: 0,
    minFundingAmount$: 8000,
    maxFundingAmount$: 250000,
    restrictedIndustries: [
      'Adult Entertainment',
      'Real Estate',
      'Construction',
      'Transportation and Warehousing',
    ],
    tier: 1,
  },
  {
    funder: 'Kapitus',
    paperType: 'A',
    minimumRevenueAnnual: 150000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 640,
    maxPosition: 2,
    position1st: 'Yes',
    stateRestrictions: [
    ],
    insuffientFundsNSF: [
      3,
      9,
    ],
    negativeDays: [
      3,
      9,
    ],
    minimumMonthlyDepositcount: 4,
    minimumTimeInBusinessMonths: 36,
    minAvgDailyBalance: 'Cover weekly payment',
    minFundingAmount$: 0,
    maxFundingAmount$: 1000000,
    restrictedIndustries: [
      'Legal Services',
      'Real Estate',
      'Agriculture, Forestry, Fishing and Hunting',
      'Finance and Insurance',
      'Automobile Dealers & Parts',
    ],
    tier: 1,
  },
  {
    funder: 'Loanbud',
    paperType: 'A',
    minimumCreditScore: 675,
    maxPosition: 5,
    position1st: 'Yes',
    stateRestrictions: [
    ],
    insuffientFundsNSF: [
    ],
    negativeDays: [
    ],
    minAvgDailyBalance: 0,
    minFundingAmount$: 25000,
    maxFundingAmount$: 5000000,
    restrictedIndustries: [
    ],
    tier: 1,
  },
  {
    funder: 'Lendini',
    pastSettledDefaults: true,
    paperType: 'B-D',
    minimumRevenueAnnual: 60000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 475,
    maxPosition: 5,
    position1st: 'Yes',
    stateRestrictions: [
      'UT',
    ],
    insuffientFundsNSF: [
      4,
      5,
    ],
    negativeDays: [
      6,
      7,
    ],
    minimumMonthlyDepositcount: 4,
    minimumTimeInBusinessMonths: 8,
    minAvgDailyBalance: 500,
    minFundingAmount$: 0,
    maxFundingAmount$: 300000,
    restrictedIndustries: [
      'Adult Entertainment',
      'Automobile Dealers & Parts',
      'Gas Stations',
      'Firearm Sales',
      'Finance and Insurance',
      'Real Estate',
    ],
    tier: 2,
  },
  {
    funder: 'Legend Advance',
    paperType: 'B',
    minimumRevenueAnnual: 300000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    maxPosition: 3,
    position1st: 'Yes',
    stateRestrictions: [
    ],
    insuffientFundsNSF: [
      4,
      12,
    ],
    negativeDays: [
      4,
      12,
    ],
    minimumMonthlyDepositcount: 3,
    minAvgDailyBalance: 1000,
    minFundingAmount$: 0,
    maxFundingAmount$: 500000,
    restrictedIndustries: [
      'Legal Services',
      'Religious Organizations',
      'Finance and Insurance',
    ],
    tier: 2,
  },
  {
    funder: 'LG funding',
    paperType: 'B',
    minimumRevenueAnnual: 250000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 600,
    maxPosition: 3,
    position1st: 'Yes',
    stateRestrictions: [
      'UT',
    ],
    insuffientFundsNSF: [
      4,
      10,
    ],
    negativeDays: [
      4,
      10,
    ],
    minimumMonthlyDepositcount: 4,
    minimumTimeInBusinessMonths: 18,
    minFundingAmount$: 10000,
    maxFundingAmount$: 1000000,
    restrictedIndustries: [
      'Automobile Dealers & Parts',
    ],
    tier: 2,
  },
  {
    funder: 'MANTIS',
    paperType: 'C-D',
    minimumRevenueAnnual: 180000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 475,
    maxPosition: 4,
    position1st: 'Yes',
    stateRestrictions: [
    ],
    insuffientFundsNSF: [
      6,
      6,
    ],
    negativeDays: [
      6,
      6,
    ],
    minimumMonthlyDepositcount: 10,
    minimumTimeInBusinessMonths: 6,
    restrictedIndustries: [
      'Automobile Dealers & Parts',
      'Finance and Insurance',
    ],
    tier: 5,
  },
  {
    funder: 'Mulligan Funding/ Mulligan Senior',
    paperType: 'A - B',
    minimumRevenueAnnual: 500000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 625,
    maxPosition: 1,
    position1st: 'Yes',
    stateRestrictions: [
    ],
    insuffientFundsNSF: [
      5,
      10,
    ],
    negativeDays: [
      5,
      10,
    ],
    minimumMonthlyDepositcount: 1,
    minimumTimeInBusinessMonths: 6,
    minAvgDailyBalance: 500,
    minFundingAmount$: 10000,
    maxFundingAmount$: 2000000,
    restrictedIndustries: [
      'Agriculture, Forestry, Fishing and Hunting',
      'Adult Entertainment',
      'Automobile Dealers & Parts',
      'Utilities',
      'Finance and Insurance',
      'Firearm Sales',
      'Gambling',
      'Legal Services',
      'Mining',
      'Oil and Gas Extraction',
      'Political, Governmental, Or Public Organizations',
      'Real Estate',
      'Travel Agencies',
    ],
    tier: 1,
  },
  {
    funder: 'OnDeck',
    paperType: 'A - B',
    minimumRevenueAnnual: 150000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 600,
    maxPosition: 2,
    position1st: 'Yes',
    stateRestrictions: [
      'NV',
      'SD',
      'ND',
    ],
    insuffientFundsNSF: [
      3,
      3,
    ],
    negativeDays: [
      2,
      2,
    ],
    minimumMonthlyDepositcount: 3,
    minimumTimeInBusinessMonths: 12,
    maxFundingAmount$: 250000,
    restrictedIndustries: [
    ],
    tier: 1,
  },
  {
    funder: 'One River',
    stateRestrictions: [
    ],
    insuffientFundsNSF: [
    ],
    negativeDays: [
    ],
    restrictedIndustries: [
    ],
    tier: 4,
  },
  {
    funder: 'QFS',
    pastSettledDefaults: true,
    paperType: 'Reverse',
    minimumRevenueAnnual: 360000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 500,
    maxPosition: 0,
    position1st: 'No',
    stateRestrictions: [
      'CA',
    ],
    insuffientFundsNSF: [
      5,
      15,
    ],
    negativeDays: [
      5,
      15,
    ],
    minimumMonthlyDepositcount: 0,
    minimumTimeInBusinessMonths: 12,
    minAvgDailyBalance: 0,
    minFundingAmount$: 30000,
    maxFundingAmount$: 5000000,
    restrictedIndustries: [
      'Gambling/Casinos',
      'Adult Entertainment',
      'Legal Services',
      'Automobile Dealers & Parts',
    ],
    tier: 5,
  },
  {
    funder: 'Rapid/ SBFS',
    minimumRevenueAnnual: 120000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 620,
    maxPosition: 3,
    position1st: 'Yes',
    stateRestrictions: [
      'NJ',
      'MT',
      'NV',
      'RI',
      'VT',
      'ND',
      'SD',
    ],
    insuffientFundsNSF: [
      6,
      6,
    ],
    negativeDays: [
      6,
    ],
    minimumMonthlyDepositcount: 3,
    minimumTimeInBusinessMonths: 36,
    restrictedIndustries: [
    ],
    tier: 1,
  },
  {
    funder: 'Rival ',
    paperType: 'B-D',
    minimumRevenueAnnual: 480000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 500,
    maxPosition: 6,
    position1st: 'Yes',
    stateRestrictions: [
      'CA',
    ],
    insuffientFundsNSF: [
      5,
      11,
    ],
    negativeDays: [
      6,
      11,
    ],
    minimumMonthlyDepositcount: 3,
    minimumTimeInBusinessMonths: 12,
    minAvgDailyBalance: 750,
    minFundingAmount$: 15000,
    maxFundingAmount$: 700000,
    restrictedIndustries: [
      'Automobile Dealers & Parts',
      'Religious Organizations',
      'Finance and Insurance',
      'Legal Services',
      'Real Estate',
      'Gas Stations',
      'Transportation and Warehousing',
    ],
    tier: 3,
  },
  {
    funder: 'Silverline',
    pastSettledDefaults: true,
    paperType: 'C-D',
    minimumRevenueAnnual: 300000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 500,
    maxPosition: 6,
    position1st: 'No',
    stateRestrictions: [
      'HI',
      'AL',
      'PR',
    ],
    insuffientFundsNSF: [
      3,
      9,
    ],
    negativeDays: [
      3,
      9,
    ],
    minimumMonthlyDepositcount: 0,
    minimumTimeInBusinessMonths: 5,
    minAvgDailyBalance: 1000,
    minFundingAmount$: 8000,
    maxFundingAmount$: 500000,
    restrictedIndustries: [
      'Automobile Dealers & Parts',
      'IT, Media or Publishing',
    ],
    tier: 5,
  },
  {
    funder: 'Smartbiz (SBA products need financials)',
    paperType: 'A',
    minimumRevenueAnnual: 150000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 700,
    maxPosition: 3,
    position1st: 'Yes',
    stateRestrictions: [
    ],
    insuffientFundsNSF: [
      2,
      2,
    ],
    negativeDays: [
    ],
    minimumTimeInBusinessMonths: 24,
    restrictedIndustries: [
    ],
    tier: 1,
  },
  {
    funder: 'Spartan Capital',
    paperType: 'B+',
    minimumRevenueAnnual: 180000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 550,
    maxPosition: 5,
    position1st: 'Yes',
    stateRestrictions: [
      'UT',
    ],
    insuffientFundsNSF: [
      5,
      15,
    ],
    negativeDays: [
      5,
      15,
    ],
    minimumMonthlyDepositcount: 5,
    minimumTimeInBusinessMonths: 12,
    minAvgDailyBalance: 500,
    minFundingAmount$: 5000,
    maxFundingAmount$: 5000000,
    restrictedIndustries: [
      'Travel Agencies',
      'Gambling',
    ],
    tier: 4,
  },
  {
    funder: 'Square',
    paperType: 'B-D',
    minimumRevenueAnnual: 480000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 500,
    maxPosition: 500,
    position1st: 'Yes',
    stateRestrictions: [
      'VA',
      'UT',
    ],
    insuffientFundsNSF: [
      5,
      12,
    ],
    negativeDays: [
      5,
      12,
    ],
    minimumMonthlyDepositcount: 3,
    minimumTimeInBusinessMonths: 12,
    minAvgDailyBalance: 750,
    minFundingAmount$: 15000,
    maxFundingAmount$: 0,
    restrictedIndustries: [
      'Transportation and Warehousing',
    ],
    tier: 3,
  },
  {
    funder: 'SWIFT ',
    paperType: 'B-C',
    minimumRevenueAnnual: 540000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 500,
    maxPosition: 5,
    position1st: 'Yes',
    stateRestrictions: [
      'UT',
      'VA',
    ],
    insuffientFundsNSF: [
      3,
      3,
    ],
    negativeDays: [
      3,
      3,
    ],
    minimumMonthlyDepositcount: 1,
    minimumTimeInBusinessMonths: 12,
    minAvgDailyBalance: '5% of Deposits',
    minFundingAmount$: 5000,
    maxFundingAmount$: 2000000,
    restrictedIndustries: [
      'Real Estate',
      'Automobile Dealers & Parts',
      'Transportation and Warehousing',
      'Religious Organizations',
    ],
    tier: 5,
  },
  {
    funder: 'TORRO',
    minimumRevenueAnnual: 120000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 500,
    maxPosition: 8,
    position1st: 'Yes',
    stateRestrictions: [
      'PR',
    ],
    insuffientFundsNSF: [
      4,
      12,
    ],
    negativeDays: [
      5,
      15,
    ],
    minimumMonthlyDepositcount: 5,
    minimumTimeInBusinessMonths: 3,
    minAvgDailyBalance: 0,
    minFundingAmount$: 5000,
    maxFundingAmount$: 250000,
    restrictedIndustries: [
      'Automobile Dealers & Parts',
      'Religious Organizations',
      'Gambling',
      'Gas Stations',
      'Transportation and Warehousing',
      'Adult Entertainment',
    ],
    tier: 5,
  },
  {
    funder: 'Upfunding',
    paperType: 'A-C',
    minimumRevenueAnnual: 108000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 550,
    maxPosition: 4,
    position1st: 'Yes',
    stateRestrictions: [
      'PR',
    ],
    insuffientFundsNSF: [
      3,
      8,
    ],
    negativeDays: [
      4,
      10,
    ],
    minimumMonthlyDepositcount: 4,
    minimumTimeInBusinessMonths: 6,
    minAvgDailyBalance: 500,
    minFundingAmount$: 5000,
    maxFundingAmount$: 45000,
    restrictedIndustries: [
      'Legal Services',
      'Finance and Insurance',
      'Gambling',
      'Firearm Sales',
    ],
    tier: 5,
  },
  {
    funder: 'Uptown Fund',
    pastSettledDefaults: true,
    paperType: 'C-D',
    minimumRevenueAnnual: 540000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 500,
    maxPosition: 6,
    position1st: 'No',
    stateRestrictions: [
      'VA',
      'UT',
    ],
    insuffientFundsNSF: [
      4,
      10,
    ],
    negativeDays: [
      4,
      11,
    ],
    minimumMonthlyDepositcount: 2,
    minimumTimeInBusinessMonths: 5,
    minAvgDailyBalance: 1500,
    minFundingAmount$: 10000,
    maxFundingAmount$: 1000000,
    restrictedIndustries: [
      'Transportation and Warehousing',
      'Automobile Dealers & Parts',
    ],
    tier: 4,
  },
  {
    funder: 'Vader',
    minimumRevenueAnnual: 48000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 500,
    maxPosition: 8,
    position1st: 'Yes',
    stateRestrictions: [
      'VA',
    ],
    insuffientFundsNSF: [
      7,
      20,
    ],
    negativeDays: [
      7,
      20,
    ],
    minimumMonthlyDepositcount: 0,
    minimumTimeInBusinessMonths: 1,
    minAvgDailyBalance: 0,
    minFundingAmount$: 2600,
    maxFundingAmount$: 15000,
    restrictedIndustries: [
      'Finance and Insurance',
      'Automobile Dealers & Parts',
      'Legal Services',
    ],
    tier: 4,
  },
  {
    funder: 'Velocity Capital Group',
    paperType: 'B-D',
    minimumRevenueAnnual: 240000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 500,
    maxPosition: 4,
    position1st: 'Yes',
    stateRestrictions: [
    ],
    insuffientFundsNSF: [
      5,
      11,
    ],
    negativeDays: [
      5,
      11,
    ],
    minimumMonthlyDepositcount: 5,
    minimumTimeInBusinessMonths: 12,
    minAvgDailyBalance: 1000,
    minFundingAmount$: 5000,
    maxFundingAmount$: 3000000,
    restrictedIndustries: [
      'Transportation and Warehousing',
      'Oil and Gas Extraction',
      'Finance and Insurance',
      'Automobile Dealers & Parts',
    ],
    tier: 4,
  },
  {
    funder: 'VITAL ',
    paperType: 'B-C',
    minimumRevenueAnnual: 250000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 520,
    maxPosition: 4,
    position1st: 'Yes',
    stateRestrictions: [
      'CA',
      'UT',
    ],
    insuffientFundsNSF: [
      5,
      5,
    ],
    negativeDays: [
      5,
      5,
    ],
    minimumMonthlyDepositcount: 5,
    minimumTimeInBusinessMonths: 12,
    minAvgDailyBalance: 1000,
    minFundingAmount$: 10000,
    maxFundingAmount$: 300000,
    restrictedIndustries: [
      'Finance and Insurance',
      ' Gas Stations',
      'Automobile Dealers & Parts',
      'Transportation and Warehousing',
      'Religious Organizations',
      'Real Estate',
      'Travel Agencies',
      'Oil and Gas Extraction',
    ],
    tier: 2,
  },
  {
    funder: 'WeFund',
    pastSettledDefaults: true,
    paperType: 'A-D',
    minimumRevenueAnnual: 360000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 0,
    maxPosition: 5,
    position1st: 'Yes',
    stateRestrictions: [
      'VA',
      'UT',
    ],
    insuffientFundsNSF: [
      3,
      7,
    ],
    negativeDays: [
      3,
      7,
    ],
    minimumMonthlyDepositcount: 4,
    minimumTimeInBusinessMonths: 7,
    minAvgDailyBalance: 0,
    minFundingAmount$: 5000,
    maxFundingAmount$: 2000000,
    restrictedIndustries: [
    ],
    tier: 4,
  },
  {
    funder: 'Wellen',
    minimumRevenueAnnual: 120000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 525,
    maxPosition: 1,
    position1st: 'Yes',
    stateRestrictions: [
      'CA',
      'UT',
      'VA',
    ],
    insuffientFundsNSF: [
      4,
      0,
    ],
    negativeDays: [
      4,
      0,
    ],
    minimumMonthlyDepositcount: 0,
    minimumTimeInBusinessMonths: 24,
    minAvgDailyBalance: 0,
    minFundingAmount$: 10000,
    maxFundingAmount$: 150000,
    restrictedIndustries: [
      'Legal Services',
      'Gas stations',
      'Firearm Sales',
      'Adult Entertainment',
      'Agriculture, Forestry, Fishing and Hunting',
      'Mining',
    ],
    tier: 1,
  },
  {
    funder: 'WIDE',
    minimumRevenueAnnual: 96000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 480,
    maxPosition: 5,
    position1st: 'Yes',
    stateRestrictions: [
    ],
    insuffientFundsNSF: [
      5,
      13,
    ],
    negativeDays: [
      5,
      13,
    ],
    minimumMonthlyDepositcount: 2,
    minimumTimeInBusinessMonths: 6,
    restrictedIndustries: [
      'Legal Services',
      'Finance and Insurance',
    ],
    tier: 3,
  },
  {
    funder: 'Zahav',
    paperType: 'B-C',
    minimumRevenueAnnual: 480000,
    minimumRevenueMonthly() { return this.minimumRevenueAnnual / 12; },
    minimumCreditScore: 500,
    maxPosition: 6,
    position1st: 'Yes',
    stateRestrictions: [
    ],
    insuffientFundsNSF: [
      6,
      18,
    ],
    negativeDays: [
      6,
      18,
    ],
    minimumMonthlyDepositcount: 4,
    minimumTimeInBusinessMonths: 12,
    minAvgDailyBalance: 'Daily Payment ',
    minFundingAmount$: 10000,
    maxFundingAmount$: 300000,
    restrictedIndustries: [
      'Transportation and Warehousing',
      'Finance and Insurance',
    ],
    tier: 5,
  },
];
export const listOfStates = [
  'AL',
  'AK',
  'AZ',
  'AR',
  'AS',
  'CA',
  'CO',
  'CT',
  'DE',
  'DC',
  'FL',
  'GA',
  'GU',
  'HI',
  'ID',
  'IL',
  'IN',
  'IA',
  'KS',
  'KY',
  'LA',
  'ME',
  'MD',
  'MA',
  'MI',
  'MN',
  'MS',
  'MO',
  'MT',
  'NE',
  'NV',
  'NH',
  'NJ',
  'NM',
  'NY',
  'NC',
  'ND',
  'MP',
  'OH',
  'OK',
  'OR',
  'PA',
  'PR',
  'RI',
  'SC',
  'SD',
  'TN',
  'TX',
  'TT',
  'UT',
  'VT',
  'VA',
  'VI',
  'WA',
  'WV',
  'WI',
  'WY',
];
export const businessTypes = [
  {
    businessType: 'Agriculture, Forestry, Fishing and Hunting',
    highRisk: 'No',
    seasonal: 'Yes (e.g., art seasons & exhibitions)',
  },
  {
    businessType: 'Arts, Entertainment and Recreation',
    highRisk: 'No',
    seasonal: 'No',
  },
  {
    businessType: 'Adult Entertainment',
    highRisk: 'No',
    seasonal: 'Yes (e.g., holidays)',
  },
  {
    businessType: 'Gambling',
    highRisk: 'Yes',
    seasonal: 'No',
  },
  {
    businessType: 'Automobile Dealers & Parts',
    highRisk: 'Yes',
    seasonal: 'Yes',
  },
  {
    businessType: 'Construction',
    highRisk: 'No',
    seasonal: 'No',
  },
  {
    businessType: 'Ecommerce',
    highRisk: 'No',
    seasonal: 'Yes',
  },
  {
    businessType: 'Education',
    highRisk: 'No',
    seasonal: 'Yes',
  },
  {
    businessType: 'Finance and Insurance',
    highRisk: 'No',
    seasonal: 'Yes',
  },
  {
    businessType: 'Healthcare',
    highRisk: 'No',
    seasonal: 'No',
  },
  {
    businessType: 'Social Assistance',
    highRisk: 'No',
    seasonal: 'Yes (tourist seasons)',
  },
  {
    businessType: 'IT, Media or Publishing',
    highRisk: 'Yes',
    seasonal: 'Yes (e.g., holiday & engagement seasons)',
  },
  {
    businessType: 'Legal Services',
    highRisk: 'No',
    seasonal: 'Yes',
  },
  {
    businessType: 'Mining',
    highRisk: 'Yes',
    seasonal: 'No',
  },
  {
    businessType: 'Oil and Gas Extraction',
    highRisk: 'Yes',
    seasonal: 'Yes (e.g., holiday sales)',
  },
  {
    businessType: 'Manufacturing',
    highRisk: 'No',
    seasonal: 'No',
  },
  {
    businessType: 'Political, Governmental, Or Public Organizations',
    highRisk: 'No',
    seasonal: 'Yes (e.g., holiday stores)',
  },
  {
    businessType: 'Real Estate',
    highRisk: 'No',
    seasonal: 'No',
  },
  {
    businessType: 'Religious Organizations',
    highRisk: 'Yes',
    seasonal: 'No',
  },
  {
    businessType: 'Restaurants and Food Services',
    highRisk: 'Yes',
    seasonal: 'Yes',
  },
  {
    businessType: 'Retail Stores',
    highRisk: 'Yes',
    seasonal: 'No',
  },
  {
    businessType: 'Firearm Sales',
  },
  {
    businessType: 'Gas Stations',
  },
  {
    businessType: 'Transportation and Warehousing',
  },
  {
    businessType: 'Freight Trucking',
  },
  {
    businessType: 'Travel Agencies',
  },
  {
    businessType: 'Utilities',
  },
  {
    businessType: 'Wholesale Trade',
  },
  {
    businessType: 'All Other',
  },
];
export const fundersIntakeCalc = (values) => {
  const filtered = values.isPastSetttled
    ? funderQualificationMatrix.filter((funder) => funder.pastSettledDefaults)
    : funderQualificationMatrix;
  return filtered.map((funder) => {
    const funderCounts = {
      funder: funder.funder,
      minAnnualRevenue: Number(funder.minimumRevenueAnnual <= values.annualRevenue),
      creditScoreSuitability: Number(funder.minimumCreditScore <= values.ficoScore),
      minimumMonthlyDeposits: Number(
        funder.minimumMonthlyDepositcount <= values.minMonthlyDepositCount,
      ),
      nSFLast30Days: 1 - Number(funder.insuffientFundsNSF[0] <= values.nSFLast30Days),
      nSFLast90Days: 1 - Number(funder.insuffientFundsNSF[1] <= values.nSFLast90Days),
      negativeDaysLast30: 1 - Number(funder.negativeDays[0] <= values.negativeDaysLast30),
      negativeDaysLast90: 1 - Number(funder.negativeDays[1] <= values.negativeDaysLast90),
      maximumPositions: 1 - Number(funder.maxPosition <= values.numberOfPositions),
      firstPosition: Number(values.numberOfPositions === 0 ? funder.position1st === 'Yes' : true),
      industryType: Number(!(funder.restrictedIndustries.indexOf(values.industry) >= 0)),
      state: Number(!funder.stateRestrictions.indexOf(values.state) >= 0),
      timeInBusiness: Number(funder.minimumTimeInBusinessMonths <= values.timeInBusiness),
      tier: funder.tier,
    };
    const trueCount = Object.values(funderCounts).filter((v) => v === 1).length;
    funderCounts.ranking = trueCount - Number(funder.tier === 1);
    return funderCounts;
  }).filter((data) => data.ranking === 12);
};
